// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cwd_deficit_cpp
List cwd_deficit_cpp(NumericVector wbal, IntegerVector doy, double thresh_drop, Nullable<int> doy_reset);
RcppExport SEXP _cwd_cwd_deficit_cpp(SEXP wbalSEXP, SEXP doySEXP, SEXP thresh_dropSEXP, SEXP doy_resetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type wbal(wbalSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type doy(doySEXP);
    Rcpp::traits::input_parameter< double >::type thresh_drop(thresh_dropSEXP);
    Rcpp::traits::input_parameter< Nullable<int> >::type doy_reset(doy_resetSEXP);
    rcpp_result_gen = Rcpp::wrap(cwd_deficit_cpp(wbal, doy, thresh_drop, doy_reset));
    return rcpp_result_gen;
END_RCPP
}
// cwd_surplus_cpp
List cwd_surplus_cpp(NumericVector wbal, IntegerVector annual_max_indices);
RcppExport SEXP _cwd_cwd_surplus_cpp(SEXP wbalSEXP, SEXP annual_max_indicesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type wbal(wbalSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type annual_max_indices(annual_max_indicesSEXP);
    rcpp_result_gen = Rcpp::wrap(cwd_surplus_cpp(wbal, annual_max_indices));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_cwd_cwd_deficit_cpp", (DL_FUNC) &_cwd_cwd_deficit_cpp, 4},
    {"_cwd_cwd_surplus_cpp", (DL_FUNC) &_cwd_cwd_surplus_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_cwd(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
